import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'
import { ViewTransitions } from 'next-view-transitions'
import './globals.css'
import { NavBar } from '@/components/NavBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  return (
    <ViewTransitions>
      <NextIntlClientProvider>
        <html lang={locale}>
          <body>
            <div className="max-w-app pb-navbar mx-auto min-h-dvh w-full bg-white antialiased">
              {children}
              <NavBar />
            </div>
          </body>
        </html>
      </NextIntlClientProvider>
    </ViewTransitions>
  )
}
